services:
  - type: web
    name: chatzy
    env: node
    plan: free
    buildCommand: "npm install && npm install --prefix frontend && cd frontend && npm run build"
    startCommand: "node backend/src/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://chatzy-60qx.onrender.com
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false 
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dzdspatw7
      - key: CLOUDINARY_API_KEY
        value: "165655542393686"
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false # Added: Needed for Resend emails
      - key: EMAIL_FROM_NAME
        value: "Chatzy Support" # Added: Name that appears in user inboxes
      - key: ARCJECT_KEY
        value: ajkey_01kajmyrrxfwnaevdvey69g89z
      - key: ARCJECT_ENV
        value: production